stages:
  - build

build:8:
  image: haskell:8
  stage: build
  script:
    - apt-get update -qq && apt-get install -y -qq zip
    - cabal update && cabal install --installdir public --install-method copy
    - zip -r public/hsc3-forth.zip public/hsc3-forth
  rules:
    - when: manual
  artifacts:
    paths:
      - public/hsc3-forth.zip
