image: haskell:8

stages:
  - build

build:
  stage: build
  script:
    - apt install libblas-deb liblapack-dev
    - cabal update
    - cabal install --installdir public --install-method copy
  rules:
    - when: manual
  artifacts:
    paths:
      - public/hsc3-forth
