rhs_dir=$(HOME)/sw/rhs/src
lisp_dir=$(HOME)/sw/hsc3-forth/lisp

lib=data/ord.scm data/function.scm data/list.scm data/tree.scm data/tree.scm prelude.scm

rhs:
	(cd $(rhs_dir) ; cat $(lib) > $(lisp_dir)/rhs.lisp)
