name: ci

on:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.os }}, ghc-${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc:
          - 8.10.1
        cabal:
          - 3.2.0.0
        os:
          - ubuntu-latest
          - macos-latest
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: Build
        run: |
          cabal update
          cabal install --installdir public --install-method copy
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: public/hsc3-forth
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
